baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Fpay'
theme = "fpay"

#  menu items

[[main]]
  name = "Inicio"
  weight = 1
  url = ""


[[menu.main]]
    name = "Documentación"
    weight = 2
    url = "docs/"


    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

    [outputs]
  home = ["HTML", "RSS","JSON"]