name = "Compose"
license = "MIT"
licenselink = "https://github.com/onweru/compose/blob/master/LICENSE"
description = "A hugo theme for documentation sites. It's inspired by forestry.io's docs page"
homepage = ""
tags = ["technical", "docs", "dark", "customizable", "search", "documentation"]
features = ["technical", "docs", "dark", "customizable", "search", "documentation"]
min_version = "0.76.0"

[author]
  name = "Wfpayeru"
  homepage = ""
